#!/bin/bash
set -e

# ============================================================
# XCH — Script d'installation automatique
# ============================================================
# Usage:
#   chmod +x install.sh
#   ./install.sh
#
# Ce script :
#   1. Verifie les prerequis (Docker, Docker Compose)
#   2. Genere des secrets cryptographiques uniques
#   3. Cree les fichiers .env (root + backend + frontend)
#   4. Build et lance tous les services Docker
#   5. Attend que le backend soit pret
#   6. Affiche l'URL du Setup Wizard
#
# Apres l'installation, ouvrez le Setup Wizard dans le navigateur
# pour configurer votre organisation, creer le compte admin,
# et optionnellement charger les donnees de demonstration.
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ===== Couleurs =====
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; exit 1; }

# ============================================================
# 1. Verifier les prerequis
# ============================================================
echo ""
echo -e "${BOLD}=========================================${NC}"
echo -e "${BOLD}   XCH — Installation automatique${NC}"
echo -e "${BOLD}=========================================${NC}"
echo ""

# Docker
if ! command -v docker >/dev/null 2>&1; then
    fail "Docker n'est pas installe. Installez Docker : https://docs.docker.com/get-docker/"
fi
ok "Docker detecte ($(docker --version | head -1))"

# Docker Compose
if ! docker compose version >/dev/null 2>&1; then
    fail "Docker Compose n'est pas installe. Installez Docker Compose v2."
fi
ok "Docker Compose detecte ($(docker compose version --short))"

# curl (pour le health check)
if ! command -v curl >/dev/null 2>&1; then
    warn "curl n'est pas installe — le health check sera ignore"
    HAS_CURL=false
else
    HAS_CURL=true
fi

# openssl (pour generer les secrets)
if ! command -v openssl >/dev/null 2>&1; then
    fail "openssl n'est pas installe. Installez-le : apt install openssl"
fi

# Verifier qu'on n'est pas deja installe
if [ -f ".env" ] && [ -f "backend/.env" ] && [ -f "frontend/.env.local" ]; then
    echo ""
    warn "Des fichiers .env existent deja !"
    echo ""
    echo "  Si vous souhaitez reinstaller, supprimez-les d'abord :"
    echo "    rm .env backend/.env frontend/.env.local"
    echo ""
    echo "  Ou pour simplement redemarrer les services :"
    echo "    docker compose up -d"
    echo ""
    read -p "Continuer et ecraser les .env existants ? [y/N] " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        info "Installation annulee."
        exit 0
    fi
fi

# ============================================================
# 2. Generer des secrets cryptographiques
# ============================================================
echo ""
info "Generation des secrets cryptographiques..."

POSTGRES_PASSWORD=$(openssl rand -hex 16)
MINIO_SECRET_KEY=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
COOKIE_SECRET=$(openssl rand -hex 16)

ok "Secrets generes (JWT: ${#JWT_SECRET} chars, DB: ${#POSTGRES_PASSWORD} chars)"

# ============================================================
# 3. Choix du mode de deploiement
# ============================================================
echo ""
echo -e "${BOLD}Mode de deploiement :${NC}"
echo ""
echo "  1) Production  — Nginx integre, ports 80/443"
echo "                    Ideal pour un serveur de production"
echo ""
echo "  2) Developpement — Ports directs exposes"
echo "                      Backend :3002, Frontend :3001"
echo "                      PostgreSQL :5433, Redis :6380"
echo ""
read -p "Choix [1/2] (defaut: 1): " MODE
MODE=${MODE:-1}

if [ "$MODE" = "2" ]; then
    COMPOSE_CMD="docker compose"
    BACKEND_PORT=3002
    FRONTEND_PORT=3001
    BACKEND_URL="http://localhost:${BACKEND_PORT}/api"
    APP_URL="http://localhost:${FRONTEND_PORT}"
    NODE_ENV="development"
    info "Mode developpement selectionne"
else
    COMPOSE_CMD="docker compose -f docker-compose.yml --profile proxy"
    BACKEND_PORT=80
    FRONTEND_PORT=80
    BACKEND_URL="http://localhost/api"
    APP_URL="http://localhost"
    NODE_ENV="production"
    info "Mode production selectionne"
fi

# ============================================================
# 4. Creer les fichiers .env
# ============================================================
echo ""
info "Creation des fichiers de configuration..."

# --- Root .env ---
cat > .env << ENVEOF
# XCH — Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# DO NOT commit this file to git

# ===== DATABASE =====
POSTGRES_USER=xch_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=xch_dev
POSTGRES_PORT=5433

# ===== REDIS =====
REDIS_PORT=6380

# ===== MINIO =====
MINIO_ACCESS_KEY=xch_minio_admin
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001

# ===== NGINX =====
HTTP_PORT=80
HTTPS_PORT=443

# ===== FRONTEND =====
FRONTEND_API_URL=
FRONTEND_APP_URL=
ENVEOF

# --- Backend .env ---
cat > backend/.env << ENVEOF
# XCH Backend — Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# DO NOT commit this file to git

# ===== DATABASE =====
DATABASE_URL="postgresql://xch_user:${POSTGRES_PASSWORD}@postgres:5432/xch_dev"

# ===== APP =====
NODE_ENV=${NODE_ENV}
PORT=3000

# ===== FRONTEND =====
FRONTEND_URL=

# ===== COOKIES =====
COOKIE_DOMAIN=
COOKIE_SECURE=false

# ===== JWT =====
JWT_SECRET="${JWT_SECRET}"
JWT_ACCESS_EXPIRATION=15m
JWT_REFRESH_EXPIRATION=7d

# ===== REDIS =====
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# ===== MINIO =====
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_ACCESS_KEY=xch_minio_admin
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_BUCKET=xch-storage
MINIO_USE_SSL=false
MINIO_PUBLIC_URL=

# ===== STORAGE =====
STORAGE_TYPE=minio
UPLOAD_DIR=./uploads
ENVEOF

# --- Frontend .env.local ---
cat > frontend/.env.local << ENVEOF
# XCH Frontend — Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# DO NOT commit this file to git

NEXT_PUBLIC_API_URL=
NEXT_PUBLIC_APP_URL=
NODE_ENV=${NODE_ENV}
ENVEOF

ok "Fichiers .env crees avec secrets uniques"
echo "     .env"
echo "     backend/.env"
echo "     frontend/.env.local"

# ============================================================
# 5. Build et lancement des services Docker
# ============================================================
echo ""
info "Construction des images Docker..."
info "Cela peut prendre 3-5 minutes lors du premier build..."
echo ""

$COMPOSE_CMD build 2>&1 | while IFS= read -r line; do
    # Afficher les lignes importantes uniquement
    if echo "$line" | grep -qE "(DONE|CACHED|ERROR|naming to|exporting)"; then
        echo "  $line"
    fi
done

ok "Images Docker construites"

echo ""
info "Demarrage des services..."
$COMPOSE_CMD up -d

# Verifier que les conteneurs sont lances
sleep 3
RUNNING=$(docker compose ps --status running --format '{{.Name}}' 2>/dev/null | wc -l)
ok "${RUNNING} conteneurs en cours d'execution"

# ============================================================
# 6. Attente du backend
# ============================================================
if [ "$HAS_CURL" = true ]; then
    echo ""
    info "Attente du demarrage du backend (migrations + initialisation)..."

    MAX_WAIT=180
    WAITED=0
    DOTS=""

    while [ $WAITED -lt $MAX_WAIT ]; do
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${BACKEND_URL}/setup/status" 2>/dev/null || echo "000")

        if [ "$STATUS" = "200" ]; then
            echo ""
            ok "Backend demarre et pret !"
            break
        fi

        sleep 5
        WAITED=$((WAITED + 5))
        DOTS="${DOTS}."
        echo -ne "\r  Attente... ${WAITED}s ${DOTS}"
    done

    if [ $WAITED -ge $MAX_WAIT ]; then
        echo ""
        warn "Le backend n'a pas repondu dans les ${MAX_WAIT}s"
        warn "Verifiez les logs : docker compose logs backend"
    fi
else
    echo ""
    info "Attendez ~30s que le backend demarre (migrations en cours)..."
    sleep 30
fi

# ============================================================
# 7. Afficher les informations de connexion
# ============================================================

# Detecter l'IP du serveur
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
echo -e "${BOLD}=========================================${NC}"
echo -e "${GREEN}${BOLD}   XCH installe avec succes !${NC}"
echo -e "${BOLD}=========================================${NC}"
echo ""
echo -e "  ${BOLD}Ouvrez votre navigateur :${NC}"
echo ""
if [ "$MODE" = "2" ]; then
    echo -e "    ${BLUE}http://${SERVER_IP}:${FRONTEND_PORT}/setup${NC}"
    echo ""
    echo "  Acces direct aux services :"
    echo "    Frontend  : http://${SERVER_IP}:3001"
    echo "    Backend   : http://${SERVER_IP}:3002/api/docs"
    echo "    MinIO     : http://${SERVER_IP}:9001"
    echo "    PostgreSQL: port 5433 (user: xch_user)"
else
    echo -e "    ${BLUE}http://${SERVER_IP}/setup${NC}"
fi
echo ""
echo -e "  ${BOLD}Le Setup Wizard va vous guider pour :${NC}"
echo "    - Nommer votre organisation"
echo "    - Creer votre compte administrateur"
echo "    - Charger les donnees de demonstration (optionnel)"
echo ""
echo -e "  ${BOLD}Commandes utiles :${NC}"
echo "    Voir les logs   : docker compose logs -f"
echo "    Logs backend    : docker compose logs -f backend"
echo "    Arreter         : docker compose down"
echo "    Redemarrer      : docker compose restart"
echo "    Status          : docker compose ps"
echo ""
echo -e "${BOLD}=========================================${NC}"
echo ""
