#!/bin/bash
# =============================================================================
# XCH — Generate Self-Signed SSL Certificate
#
# Usage: bash scripts/generate-ssl.sh [IP_OR_DOMAIN]
# Default: auto-detects server IP
#
# Creates:
#   docker/nginx/ssl/cert.pem
#   docker/nginx/ssl/key.pem
#   docker/nginx/conf.d/ssl.conf
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SSL_DIR="${PROJECT_DIR}/docker/nginx/ssl"
CONF_DIR="${PROJECT_DIR}/docker/nginx/conf.d"

# Determine subject (IP or domain)
if [ -n "${1:-}" ]; then
  SUBJECT="$1"
else
  SUBJECT=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
fi

echo "======================================"
echo "  XCH — SSL Certificate Generator"
echo "  Subject: ${SUBJECT}"
echo "======================================"
echo ""

# Check openssl
if ! command -v openssl &> /dev/null; then
  echo "ERROR: openssl is not installed."
  exit 1
fi

# Create directories
mkdir -p "${SSL_DIR}" "${CONF_DIR}"

# Determine SAN (Subject Alternative Name)
# If it looks like an IP, use IP:xxx — otherwise use DNS:xxx
if echo "$SUBJECT" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
  SAN="IP:${SUBJECT}"
else
  SAN="DNS:${SUBJECT}"
fi

echo "[1/3] Generating self-signed certificate..."

# Idempotence : un cert existant est conserve (sinon chaque re-run
# genererait un nouveau cert => nouvel avertissement navigateur a
# re-accepter). Forcer la regeneration : FORCE_CERT=1 bash scripts/generate-ssl.sh
if [ -f "${SSL_DIR}/cert.pem" ] && [ "${FORCE_CERT:-0}" != "1" ]; then
  echo "  Certificate deja present, conserve : ${SSL_DIR}/cert.pem"
  echo "  (FORCE_CERT=1 pour regenerer)"
else
  openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -keyout "${SSL_DIR}/key.pem" \
    -out "${SSL_DIR}/cert.pem" \
    -subj "/CN=${SUBJECT}/O=XCH/C=FR" \
    -addext "subjectAltName=${SAN}" \
    2>/dev/null

  echo "  Certificate: ${SSL_DIR}/cert.pem"
  echo "  Private key: ${SSL_DIR}/key.pem"
fi

# ── Generate SSL nginx config ───────────────────────────────────────────────
echo "[2/3] Generating nginx SSL configuration..."

cat > "${CONF_DIR}/ssl.conf" <<'NGINX'
# =============================================================================
# XCH — HTTPS Server Block (auto-generated by generate-ssl.sh)
# =============================================================================

server {
    listen 443 ssl;
    http2 on;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Security headers
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    # PAS de Strict-Transport-Security ici : avec un certificat auto-signe,
    # HSTS rend l'avertissement navigateur NON contournable (Chrome retire
    # le bouton "Continuer vers le site"). N'activer HSTS qu'avec un
    # certificat reconnu (CA interne deployee sur les postes, ou Let's Encrypt).

    # Backend API
    # NB: resolver 127.0.0.11 + proxy_pass en variable (defini dans nginx.conf
    # http{}) => re-resolution DNS a chaque TTL, pas de 502 apres recreation
    # des conteneurs backend/frontend.
    location /api/ {
        set $backend_upstream http://backend:3000;
        proxy_pass $backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # MinIO storage (public files)
    location /storage/ {
        rewrite ^/storage/(.*) /$1 break;
        set $minio_upstream http://minio:9000;
        proxy_pass $minio_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache_valid 200 1h;
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }

    # Frontend (Next.js)
    location / {
        set $frontend_upstream http://frontend:3001;
        proxy_pass $frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # Health check
    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
NGINX

echo "  Config: ${CONF_DIR}/ssl.conf"

# ── Reminder ────────────────────────────────────────────────────────────────
echo "[3/3] Done!"
echo ""
echo "======================================"
echo "  SSL certificate generated."
echo ""
echo "  Next steps:"
echo "    1. Set COOKIE_SECURE=true in backend/.env"
echo "    2. Restart the stack:"
echo "       docker compose restart nginx"
echo ""
echo "  Note: Browsers will show a security warning"
echo "  for self-signed certificates — this is normal."
echo "======================================"
