-- Add missing PinType enum values
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'ROUTER';
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'TEAMS_ROOM';
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'WEBCAM';
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'DISPLAY';
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'SERVER';
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'PDU';
ALTER TYPE "PinType" ADD VALUE IF NOT EXISTS 'BOX_5G';
